version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/nextjs
hooks:
  BeforeInstall:
    - location: deploy_scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy_scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: deploy_scripts/validate_server.sh
      timeout: 300
      runas: root