version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my-app
permissions:
  - object: /home/ec2-user/my-app
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: deploy_scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: deploy_scripts/after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: deploy_scripts/start_server.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: deploy_scripts/validate_server.sh
      timeout: 300
      runas: ec2-user