version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/my-app
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ec2-user/my-app
    owner: ec2-user
    mode: 777
hooks:
  ApplicationStop:
    - location: deploy_scripts/step1_application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: deploy_scripts/step2_before_install.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: deploy_scripts/step3_after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: deploy_scripts/step4_application_start.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: deploy_scripts/step5_validate_server.sh
      timeout: 300
      runas: ec2-user