version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing dependencies
      - npm install -g next
      - npm install -g typescript
      - npm install
  build:
    commands:
      - echo Building nextjs app
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'