version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing dependencies
      - npm install
  build:
    commands:
      - echo Building nextjs app
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - .next/**/*
    - package.json
    - next.config.js
    - next-i18next.config.js
    - tsconfig.json
    - tsconfig.server.json
    - appspec.yml